#balancing traffic

upstream notes_back {
    # Default round-robin for balance traffic
    server 127.0.0.1:8081 max_fails=3 fail_timeout=2s;
    server 127.0.0.1:8082 max_fails=3 fail_timeout=2s;
    server 127.0.0.1:8083 max_fails=3 fail_timeout=2s;
}

server {
    listen 443 ssl;
    server_name localhost;
    
    ssl_certificate     /opt/homebrew/etc/my_certs/localhost.crt;
    ssl_certificate_key /opt/homebrew/etc/my_certs/localhost.key;
    
    location / {
	proxy_pass http://notes_back;
	
	proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 2s;
        proxy_read_timeout 2s;
        proxy_send_timeout 2s;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
    }
}
